### ISSUE TITLE
STM32F401RET6

### ISSUE THREAD

**Issue by r13doc** [jbaumann/SuperPowerFirmware#5]
Hi could you help me?
I have my board creating from schematics  SensorsIot / SuperPower for Raspberry pi.
And it is intresting  for  SensorsIot / SuperPower Rpi schematics need a  stm32f412ret6, but in your firmware we can use stm32f411ret6. 
Can I use for my board stm32f401ret6 - it is pins the same, only  Data RAM Size  smaller????
THANKS!!!!

**Comment by jbaumann** [comment]
We have used both the STM32F411RET6 and the STM32F412RET6, and the firmware works with both. We currently need about 70K of RAM for the firmware, which means the STM32F401RET6 doesn't have enough RAM. With a bit of work and optimization the needed RAM could probably be brought down the the size the STM32F401 offers, but we are currently focusing on migrating the the RP2040 instead.
So, if you have some experience in developing for the STM32, with HAL and with FreeRTOS, then this could be a good exercise to understand the firmware in depth.

**Comment by r13doc** [comment]
ok, thanks
